#!/usr/bin/env python3
"""Repair mechanical corruption in Hindi text inside data files.

ACCURACY-FIRST DESIGN.

The Hindi text in src/data/qa-bhagavad-dharma.ts (and a few other files) was
extracted from a PDF/Word source with a buggy pipeline that produced two kinds
of artifacts:

  A. Doubled vowel-signs (matras) -- e.g. मुुख, अग्नििu, कुुछ.
     These are NEVER legal in Hindi orthography. A consonant can carry at most
     one matra. Safe to collapse mechanically.

  B. Doubled trailing consonants after a halant -- e.g. अर्थथ, कर्मम, स्वर्गग.
     Here the corruption duplicated the second consonant of a half-form pair.
     UNSAFE TO GENERALIZE: legitimate Hindi words do have सीधा consonant
     repetition after halant. Examples that MUST NOT be touched:
       अध्ययन  (adhyayan, "study")        — ध्+य+य+न  legitimate
       व्यय     (vyay, "expense")           — व्+य+य    legitimate
       रिक्तता  (riktata, "emptiness")      — क्+त+त+ा  legitimate (ता suffix)
       तत्त्व   (tattva, "essence")          — त्+त+्+व  legitimate
       सत्ता    (satta, "power")             — त्+त+ा    legitimate
     A blanket regex was experimentally shown to mangle these.

DECISIONS:

  * Apply (A) automatically -- mechanical, lossless, never wrong.
  * For (B), use an explicit allowlist of known-corrupt -> known-correct
    mappings, mined and confirmed by hand. Anything not on the allowlist is
    left untouched (and reported for human review). This is far smaller than
    "fix everything via regex" but it is correct.
  * Replacement-char (U+FFFD) cases are extracted to a review file. Cannot be
    auto-fixed -- information is lost.

Usage:
  python3 scripts/fix-hindi-corruption.py [--dry-run]
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

TARGET_FILES = [
    "src/data/qa-brahmbodhi.ts",
    "src/data/qa-bhagavad-dharma.ts",
    "src/data/stories.ts",
    "src/app/sanatan-seva-nidhi/content.ts",
]

REVIEW_FILE = ROOT / "scripts" / "hindi-fffd-review.txt"
HALANT_REVIEW_FILE = ROOT / "scripts" / "hindi-halant-doubling-review.txt"

# ---------------------------------------------------------------------------
# Phase A: matra and other ALWAYS-illegal doublings. Safe regex.
# ---------------------------------------------------------------------------
HALANT = "\u094D"

ALWAYS_ILLEGAL_DOUBLES = [
    # Double vowel signs (matras): impossible in legal Hindi
    (re.compile(r"\u0941{2,}"), "\u0941"),  # ुु -> ु   (u-matra)
    (re.compile(r"\u093F{2,}"), "\u093F"),  # िि -> ि   (short-i)
    (re.compile(r"\u0940{2,}"), "\u0940"),  # ीी -> ी   (long-i)
    (re.compile(r"\u0942{2,}"), "\u0942"),  # ूू -> ू   (long-u)
    (re.compile(r"\u0943{2,}"), "\u0943"),  # ृृ -> ृ   (vocalic-r)
    (re.compile(r"\u0944{2,}"), "\u0944"),  # ॄॄ -> ॄ   (vocalic-rr)
    (re.compile(r"\u0947{2,}"), "\u0947"),  # ेे -> े   (e)
    (re.compile(r"\u0948{2,}"), "\u0948"),  # ैै -> ै   (ai)
    (re.compile(r"\u094B{2,}"), "\u094B"),  # ोो -> ो   (o)
    (re.compile(r"\u094C{2,}"), "\u094C"),  # ौौ -> ौ   (au)
    (re.compile(r"\u093E{2,}"), "\u093E"),  # ाा -> ा   (long-a)
    (re.compile(r"\u0945{2,}"), "\u0945"),  # ॅॅ -> ॅ
    (re.compile(r"\u0946{2,}"), "\u0946"),
    (re.compile(r"\u0949{2,}"), "\u0949"),
    (re.compile(r"\u094A{2,}"), "\u094A"),
    # Anusvara / chandrabindu / visarga doubled (only one nasal mark per syllable is legal)
    (re.compile(r"\u0902{2,}"), "\u0902"),  # ंं -> ं
    (re.compile(r"\u0901{2,}"), "\u0901"),  # ँँ -> ँ
    (re.compile(r"\u0903{2,}"), "\u0903"),  # ःः -> ः
    # Doubled halant
    (re.compile(rf"{HALANT}{{2,}}"), HALANT),
    # Halant followed directly by anusvara/chandrabindu -- corruption artifact
    # NOTE: only when halant has no consonant after it (orphan halant). Skip --
    # the matra fixes above usually expose this and orphan halants are rare.
]


# ---------------------------------------------------------------------------
# Phase B: explicit allowlist of corrupt-token -> corrected-token.
#
# Generated by mining the file for the pattern (C)्\1\1+ and then manually
# vetting each candidate against a Hindi dictionary. Tokens listed here are
# unambiguous OCR artifacts. Anything NOT on this list (e.g. अध्ययन, व्यय,
# रिक्तता) is left untouched.
#
# Add to this list as new corrupt forms are found. Use sandhi-aware boundaries:
# we replace whole substrings, not standalone words, because the corrupt text
# often has these joined to other characters.
# ---------------------------------------------------------------------------
HALANT_DOUBLING_ALLOWLIST: dict[str, str] = {
    # -र्थ- family
    "अर्थथ": "अर्थ",          # meaning
    "स्वार्थथ": "स्वार्थ",     # selfishness
    "परमार्थथ": "परमार्थ",
    "व्यर्थथ": "व्यर्थ",
    "तीर्थथ": "तीर्थ",
    "यथार्थथ": "यथार्थ",
    "पदार्थथ": "पदार्थ",
    "अनर्थथ": "अनर्थ",
    "समर्थथ": "समर्थ",
    "व्यार्थथ": "व्यार्थ",
    # -र्म- family
    "कर्मम": "कर्म",
    "धर्मम": "धर्म",
    "मर्मम": "मर्म",
    "वर्मम": "वर्म",
    "नर्मम": "नर्म",
    "जन्मम": "जन्म",          # ् + म + म (corruption of जन्म? unusual but observed)
    # -र्ण- family
    "पूर्णण": "पूर्ण",
    "वर्णण": "वर्ण",
    "स्वर्णण": "स्वर्ण",
    "अपूर्णण": "अपूर्ण",
    "सम्पूर्णण": "सम्पूर्ण",
    "संपूर्णण": "संपूर्ण",
    "वर्णणन": "वर्णन",        # description
    # -र्ग- family
    "स्वर्गग": "स्वर्ग",
    "मार्गग": "मार्ग",
    "वर्गग": "वर्ग",
    "उद्वेगग": "उद्वेग",
    "त्यागग": "त्याग",
    "योगग": "योग",
    "उपयोगग": "उपयोग",
    "रोगग": "रोग",
    "योगगी": "योगी",
    # -र्श- family
    "दर्शशन": "दर्शन",
    "स्पर्शश": "स्पर्श",
    "मार्गदर्शशन": "मार्गदर्शन",
    # -र्व- family
    "पूर्वव": "पूर्व",
    "सर्वव": "सर्व",
    "गर्वव": "गर्व",
    "पर्वव": "पर्व",
    "उत्सवव": "उत्सव",
    # -र्य- family (corrupt double य after र्). NOTE: do not confuse with
    # legitimate words. Words like कार्य, अनिवार्य are correct with single य.
    # The corruption duplicates: कार्ययक्रम, अनिवार्ययता.
    "कार्यय": "कार्य",
    "अनिवार्यय": "अनिवार्य",
    "आचार्यय": "आचार्य",
    "सूर्यय": "सूर्य",
    "मूर्यय": "मूर्य",
    "अर्पपण": "अर्पण",
    "समर्पपण": "समर्पण",
    "तर्पपण": "तर्पण",
    "आरोपपण": "आरोपण",
    "तर्कक": "तर्क",
    "अर्कक": "अर्क",
    "मर्कक": "मर्क",
    "खर्चच": "खर्च",
    "खर्चचा": "खर्चा",
    "उच्चच": "उच्च",          # but careful: उच्चचरित = उच्च+चरित is real. Use explicit form.
    # Halant + consonant + duplicated consonant (other less common families)
    "स्वच्छछ": "स्वच्छ",
    "स्पष्टट": "स्पष्ट",
    "इष्टट": "इष्ट",
    "नष्टट": "नष्ट",
    "कष्टट": "कष्ट",
    "श्रेष्ठठ": "श्रेष्ठ",
    "निष्ठठ": "निष्ठ",
    "तुष्टट": "तुष्ट",
    "दुष्टट": "दुष्ट",
    # Round 2: entries below were hand-verified as corruption (not legitimate
    # double-consonant Hindi words like अध्ययन / व्यय / रिक्तता).
    "वर्षष": "वर्ष",
    "वर्कक": "वर्क",
    "आकर्षषण": "आकर्षण",
    "गर्भभ": "गर्भ",
    "दर्दद": "दर्द",
    "दर्यय": "दर्य",
    "दर्पपण": "दर्पण",
    "आदर्शश": "आदर्श",
    "हर्जज": "हर्ज",
    "अथर्वव": "अथर्व",
    "पर्ससन": "पर्सन",
    "कर्जज": "कर्ज",
    "दर्शशक": "दर्शक",
    "र्जजन": "र्जन",
    "फर्कक": "फर्क",
    "दर्जजन": "दर्जन",
    "टर्मम": "टर्म",
    "बर्चच": "बर्च",
    "मर्जज": "मर्ज",
    "भरतर्षषभ": "भरतर्षभ",
    "आर्जजव": "आर्जव",
    # Round 3 additions discovered after PDF re-extraction
    "चर्चाचा": "चर्चा",         # discussion (corruption duplicates चा)
    "निष्कर्षष": "निष्कर्ष",     # conclusion
    "उत्कर्षष": "उत्कर्ष",       # excellence
    "संदर्शश": "संदर्श",         # related/inspection
    "विमर्शश": "विमर्श",         # consultation
    "हर्षष": "हर्ष",             # joy
    # Compound forms where the inner -र्म- gets duplicated mid-word (the
    # word-final -कर्मम variants are already caught above).
    "कर्ममयोगी": "कर्मयोगी",
    "कर्ममफल": "कर्मफल",
    "कर्ममबन्धनैः": "कर्मबन्धनैः",
    # Round 4: residuals found after first PDF extraction pass.
    "सिर्फफ": "सिर्फ",            # only (very common)
    "ब्रह्मचर्यय": "ब्रह्मचर्य",   # celibacy
    "संदर्भभ": "संदर्भ",          # context/reference
    "शंकराचार्यय": "शंकराचार्य",   # Shankaracharya
    "निर्ममल": "निर्मल",          # pure
    "निर्भभर": "निर्भर",          # dependent
    "अर्घ्यय": "अर्घ्य",          # offering
    "संपर्कक": "संपर्क",          # contact
    "पार्थथ": "पार्थ",            # Partha (Arjuna)
    "दुर्घघटना": "दुर्घटना",       # accident
    "निर्णणय": "निर्णय",          # decision
    "आश्चर्यय": "आश्चर्य",        # surprise
    "धैर्यय": "धैर्य",            # patience
    "सार्थथक": "सार्थक",          # meaningful
    "कर्ततव्य": "कर्तव्य",         # duty
    "दुर्जजय": "दुर्जय",          # invincible
    "विशेषष": "विशेष",            # special
    "अंशश": "अंश",                # portion
    "सर्वज्ञज्ञ": "सर्वज्ञ",       # omniscient
    "कर्ततृत्व": "कर्तृत्व",       # agency
    "ईश्वरत्वव": "ईश्वरत्व",       # divinity
}

# Compile allowlist into a single alternation regex (longest first to avoid
# prefix collisions).
_keys_sorted = sorted(HALANT_DOUBLING_ALLOWLIST.keys(), key=len, reverse=True)
ALLOWLIST_RE = re.compile("|".join(re.escape(k) for k in _keys_sorted))


# ---------------------------------------------------------------------------
# Phase C: just count remaining `(C)्\1\1+` patterns so we can report what is
# left for human review.
# ---------------------------------------------------------------------------
CONS = r"[\u0915-\u0939\u0958-\u095F]"
REMAINING_HALANT_DOUBLING_RE = re.compile(rf"\w*{CONS}{HALANT}({CONS})\1+\w*")


def apply_always_illegal(text: str) -> tuple[str, int]:
    total = 0
    for pat, repl in ALWAYS_ILLEGAL_DOUBLES:
        text, n = pat.subn(repl, text)
        total += n
    return text, total


def apply_allowlist(text: str) -> tuple[str, int]:
    """Apply word-level allowlist replacements."""
    n = 0

    def _repl(m: re.Match) -> str:
        nonlocal n
        n += 1
        return HALANT_DOUBLING_ALLOWLIST[m.group(0)]

    new_text = ALLOWLIST_RE.sub(_repl, text)
    return new_text, n


FFFD = "\uFFFD"


def collect_fffd(text: str, rel_path: str) -> list[str]:
    out = []
    for ln_idx, line in enumerate(text.split("\n"), 1):
        if FFFD not in line:
            continue
        for m in re.finditer(re.escape(FFFD), line):
            i = m.start()
            left = line[max(0, i - 35) : i]
            right = line[i + 1 : i + 36]
            out.append(f"{rel_path}:{ln_idx}: ...{left}[\uFFFD]{right}...")
    return out


def collect_remaining_doublings(text: str, rel_path: str) -> Counter:
    """Find every (C)्CC+ token still present (i.e. NOT on the allowlist).

    Returns Counter of token -> count, so the human reviewer can decide which
    are real Hindi words (e.g., अध्ययन) and which are new corruption forms to
    add to the allowlist.
    """
    counts: Counter = Counter()
    # Tokenize on whitespace and TS-quote chars
    for token in re.findall(r"[\w\u0900-\u097F]+", text):
        if REMAINING_HALANT_DOUBLING_RE.fullmatch(token):
            counts[token] += 1
    return counts


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    all_fffd: list[str] = []
    all_remaining: Counter = Counter()
    grand_a = 0
    grand_b = 0

    for rel in TARGET_FILES:
        p = ROOT / rel
        if not p.exists():
            print(f"SKIP (missing): {rel}")
            continue
        text = p.read_text(encoding="utf-8")

        all_fffd.extend(collect_fffd(text, rel))

        text_a, n_a = apply_always_illegal(text)
        text_ab, n_b = apply_allowlist(text_a)
        grand_a += n_a
        grand_b += n_b

        # Count remaining suspicious tokens AFTER our edits
        remaining = collect_remaining_doublings(text_ab, rel)
        for tok, c in remaining.items():
            all_remaining[(rel, tok)] += c

        print(f"  {rel}: matra fixes={n_a}, allowlist fixes={n_b}")

        if not args.dry_run and (n_a or n_b):
            p.write_text(text_ab, encoding="utf-8")

    # FFFD report
    if all_fffd:
        header = (
            f"# U+FFFD (replacement char) occurrences requiring manual review\n"
            f"# Total: {len(all_fffd)}\n"
            f"# Each line: file:lineno: ...<left>[\uFFFD]<right>...\n"
            f"# These cannot be auto-fixed; the lost character must be inferred\n"
            f"# from the original Hindi source.\n\n"
        )
        body = "\n".join(all_fffd) + "\n"
        if args.dry_run:
            print(
                f"\n(dry-run) Would write {len(all_fffd)} FFFD entries to {REVIEW_FILE.relative_to(ROOT)}"
            )
        else:
            REVIEW_FILE.write_text(header + body, encoding="utf-8")
            print(f"\nWrote {len(all_fffd)} FFFD entries -> {REVIEW_FILE.relative_to(ROOT)}")

    # Remaining-doubling report (tokens NOT auto-fixed; reviewer should decide
    # which are real Hindi and which to add to the allowlist).
    if all_remaining:
        # Aggregate by token across files
        token_totals: Counter = Counter()
        token_files: dict[str, set[str]] = {}
        for (rel, tok), c in all_remaining.items():
            token_totals[tok] += c
            token_files.setdefault(tok, set()).add(rel)

        lines = [
            "# Tokens matching pattern (C)्CC+ that were NOT auto-fixed.",
            "# REVIEWER: for each token, decide:",
            "#   - Real Hindi word (e.g. अध्ययन, व्यय, रिक्तता, तत्त्व, सत्ता): leave as-is.",
            "#   - Corruption (e.g. कर्मम, अर्थथ): add to HALANT_DOUBLING_ALLOWLIST in",
            "#     scripts/fix-hindi-corruption.py and re-run.",
            "# Format: <count>\t<token>\t<files>",
            "",
        ]
        for tok, cnt in token_totals.most_common():
            files_str = ", ".join(sorted(token_files[tok]))
            lines.append(f"{cnt}\t{tok}\t{files_str}")

        report = "\n".join(lines) + "\n"
        if args.dry_run:
            print(
                f"(dry-run) Would write {len(token_totals)} distinct unhandled tokens to {HALANT_REVIEW_FILE.relative_to(ROOT)}"
            )
        else:
            HALANT_REVIEW_FILE.write_text(report, encoding="utf-8")
            print(
                f"Wrote {len(token_totals)} distinct unhandled tokens -> {HALANT_REVIEW_FILE.relative_to(ROOT)}"
            )

    mode = "would apply" if args.dry_run else "applied"
    print()
    print(f"Total matra fixes {mode}: {grand_a}")
    print(f"Total allowlist fixes {mode}: {grand_b}")
    print(f"Total U+FFFD flagged for review: {len(all_fffd)}")
    print(f"Total unhandled doubling tokens flagged for review: {len(set(t for (_, t) in all_remaining))}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
